In [18]:
import numpy as np
import pandas as pd
import seaborn as sb
dataset = pd.read_csv('mmreg.csv',delimiter=',')
del dataset['locus_of_control']
del dataset['female']
dataset = dataset.T
dataset = dataset.dropna(how='any',axis=0)
cov_mat = np.cov(dataset)


s_xx = cov_mat[0:2,0:2]
s_xy = cov_mat[2:,0:2]
s_yx = s_xy.T
s_yy = cov_mat[2:,2:]

In [19]:
s_yy

array([[102.07026375,  61.76924321,  64.61061119,  67.73028436],
       [ 61.76924321,  94.60392652,  57.93453406,  53.73156316],
       [ 64.61061119,  57.93453406,  88.6372611 ,  59.3544207 ],
       [ 67.73028436,  53.73156316,  59.3544207 ,  94.2099054 ]])

In [16]:
s_xy.shape

(4, 2)

In [17]:
s_xy

array([[0.43234156, 0.72925556],
       [0.13345867, 0.84754688],
       [0.35600743, 0.62925125],
       [0.47815888, 0.3847852 ]])

In [4]:
dataset

0      1      2      3      4      5      6      7      8    \
self_concept  -0.24  -0.47   0.59   0.28   0.03   0.90   0.03  -0.59   0.03   
motivation     1.00   0.67   0.67   0.67   1.00   0.33   0.67   0.67   1.00   
read          54.80  62.70  60.60  62.70  41.60  62.70  41.60  44.20  62.70   
write         64.50  43.70  56.70  56.70  46.30  64.50  39.10  39.10  51.50   
math          44.50  44.70  70.50  54.70  38.40  61.40  56.30  46.30  54.40   
science       52.60  52.60  58.00  58.00  36.30  58.00  45.00  36.30  49.80   

                9    ...      590    591    592    593    594   595    596  \
self_concept   0.03  ...     0.03   0.56   0.03   0.03   0.03  -0.3   0.03   
motivation     0.67  ...     1.00   0.67   0.33   0.33   1.00   1.0   1.00   
read          62.70  ...    54.80  65.40  44.20  62.70  52.10  60.1  65.40   
write         64.50  ...    59.30  67.10  54.10  54.10  56.70  67.1  56.70   
math          38.30  ...    46.20  63.00  40.30  64.70  62.80  52.4  65.40   
science       55.80  ...    47.10  66.10  52.60  58.00  47.10  55.3  58.00   

                597    598    599  
self_concept   0.03   0.03   0.03  
motivation     1.00   1.00   0.67  
read          65.40  54.80  49.50  
write         51.50  54.10  51.50  
math          61.40  66.40  55.50  
science       60.70  41.70  44.40  

[6 rows x 600 columns]

In [7]:
cov_mat

array([[4.97747906e-01, 6.97763634e-02, 4.32341555e-01, 1.33458667e-01,
        3.56007429e-01, 4.78158876e-01],
       [6.97763634e-02, 1.17463411e-01, 7.29255565e-01, 8.47546884e-01,
        6.29251252e-01, 3.84785198e-01],
       [4.32341555e-01, 7.29255565e-01, 1.02070264e+02, 6.17692432e+01,
        6.46106112e+01, 6.77302844e+01],
       [1.33458667e-01, 8.47546884e-01, 6.17692432e+01, 9.46039265e+01,
        5.79345341e+01, 5.37315632e+01],
       [3.56007429e-01, 6.29251252e-01, 6.46106112e+01, 5.79345341e+01,
        8.86372611e+01, 5.93544207e+01],
       [4.78158876e-01, 3.84785198e-01, 6.77302844e+01, 5.37315632e+01,
        5.93544207e+01, 9.42099054e+01]])


The following command must be run outside of the IPython shell:

    $ pip install librosa

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/
